// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk7khqbeU6LUbpX0S1xK5O3oR_mZ4mqbg',
    appId: '1:117721238163:web:e88bfec9ce9a706524db66',
    messagingSenderId: '117721238163',
    projectId: 'sharelearning-379604',
    authDomain: 'sharelearning-379604.firebaseapp.com',
    storageBucket: 'sharelearning-379604.appspot.com',
    measurementId: 'G-9KEDQ7Q4K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9aoB5IBSjEigoBKWgUtWVifcTBolOkZo',
    appId: '1:117721238163:android:89d4ced47092aca424db66',
    messagingSenderId: '117721238163',
    projectId: 'sharelearning-379604',
    storageBucket: 'sharelearning-379604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9eKrojws-z_aQKRts6bWeAmLDGlHzZSA',
    appId: '1:117721238163:ios:5b1a45e794266e1324db66',
    messagingSenderId: '117721238163',
    projectId: 'sharelearning-379604',
    storageBucket: 'sharelearning-379604.appspot.com',
    androidClientId:
        '117721238163-618v173cte10mqjurff1u01kgimp8kg1.apps.googleusercontent.com',
    iosClientId:
        '117721238163-5k3bsqngnma2jjfr4kjbgj5miada4q32.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareLearning',
  );
}
